- name: functions and covert sting to list
  hosts: local
  connection: local
  vars: 
   technologies: java, devops, sql, python
   tags:
      application: roboshop
      environment: dev

   listtags:
     - key: application
       value: roboshop
     - key: environment
       value: dev
  tasks:
  - name: default variable
    ansible.builtin.debug:
     msg: "{{ name | default('sowji')}}"
  - name: strings to list
    # ansible.builtin.debug:
    #  masg: "technologies are:{{ technologies | spilt(',') }} "
    ansible.builtin.debug:
        msg: "{{ technologies | split(',') }}"
  - name: tags to list
    ansible.builtin.debug:
      msg: "tags are: {{ tags | dict2items }}"
  - name: tags to list
    ansible.builtin.debug:
      msg: "tags are: {{ listtags | items2dict }}"

  - name: copy a file content into variable 
    ansible.builtin.set_fact:
      student_details: "{{ lookup('file','student.yaml') | from_yaml }}"
  
  - name: convert yaml to json
    ansible.builtin.debug:
       msg: "{{ student_details | to_json }}"

  - name: convert yaml to json
    ansible.builtin.copy:
       dest: ./student-data.json
       src: "{{ student_details | to_json }}"

 